<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-e76b91
Date:    2017-04-12 20:46:16
Version: v1.2.10
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-bdd8a3",
    "email": {
        "to": "sam@onthebarrelhead.com",
        "cc": "",
        "bcc": "",
        "subject": "Form Submission",
        "template": "",
        "sendmail_from": "sam@onthebarrlehead.com"
    },
    "admin": {
        "users": "admin:37164",
        "dataDelivery": "emailAndFile",
        "save2dbExample": true,
        "limitActivity": {
            "enabled": false,
            "by": "ip"
        }
    },
    "thankyou": {
        "url": "",
        "message": "{f1}, your form has been sent. Thank You!",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "sam@onthebarrlehead.com",
        "password": "Bear3232",
        "port": "465",
        "security": "ssl"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "How much money do you need",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": true,
                        "val": "35000"
                    },
                    "min": {
                        "enabled": false,
                        "val": "500"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "description": "Needs to be under $35,000",
                "placeholder": "5000",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-usd"
                }
            },
            "id": "f5",
            "cid": "c30"
        },
        {
            "label": "What will you use the money for?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Home Improvement",
                        "value": "HOMEIMP",
                        "checked": false
                    },
                    {
                        "label": "Major Purchase",
                        "checked": false,
                        "value": "MAJORPURCHASE"
                    },
                    {
                        "label": "Credit Card Refinance",
                        "checked": false,
                        "value": "CCREFI"
                    },
                    {
                        "label": "Business Expense",
                        "checked": false,
                        "value": "BUSINESS"
                    },
                    {
                        "label": "Vacation",
                        "value": "VACATION",
                        "checked": null
                    },
                    {
                        "label": "Wedding",
                        "value": "WEDDING",
                        "checked": null
                    },
                    {
                        "label": "Moving",
                        "value": "MOVING",
                        "checked": null
                    },
                    {
                        "label": "Medical Expense",
                        "value": "MEDICAL",
                        "checked": null
                    },
                    {
                        "label": "Vehicle Financing",
                        "value": "CARFINANCING",
                        "checked": null
                    },
                    {
                        "label": "Other",
                        "value": "OTHER",
                        "checked": null
                    },
                    {
                        "label": "Debt Consolidation",
                        "value": "DEBTCONSOLIDATION",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f7",
            "cid": "c47"
        },
        {
            "label": "First Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "firstname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "lastname",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f6",
            "cid": "c36"
        },
        {
            "label": "How would you rate your credit?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Excellent",
                        "value": "EXCELLENT",
                        "checked": false
                    },
                    {
                        "label": "Good",
                        "checked": false,
                        "value": "SOMECREDITPROBLEMS"
                    },
                    {
                        "label": "Fair",
                        "checked": false,
                        "value": "MAJORCREDITPROBLEMS"
                    },
                    {
                        "label": "Poor",
                        "checked": false,
                        "value": "LITTLEORNOCREDITHISTORY"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f8",
            "cid": "c57"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                },
                "description": "We hate SPAM."
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Please enter your address",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "labelHide": false,
            "gMapApiKey": "AIzaSyCbmivB6t7_RpS71UFr3iftZBYjYBDONPw",
            "gaCompleteEnabled": true,
            "gaCountryRestrictions": "us",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "",
            "showLabel": true,
            "showPlaceholder": true,
            "showDescription": false,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Address",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "1234 Main St.",
                        "description": "Street address, P.O. box, company name, c\/o",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line 2",
                    "field_options": {
                        "enabled": true,
                        "placeholder": "Unit 1234",
                        "description": "Apartment, suite, unit, building, floor, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "City",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "City",
                        "description": "City",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "State",
                        "description": "State \/ Province \/ Region",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "Zip Code",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "Zip Code",
                        "description": "Postal \/ Zip Code",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": false,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "Country",
                        "description": "Country",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Date of Birth",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "format": "mm\/dd\/yyyy"
                },
                "description": "mm\/dd\/yyyy",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f9",
            "cid": "c65"
        },
        {
            "label": "Home Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": false,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    },
                    "phonenumber": {
                        "enabled": true
                    }
                },
                "description": "You'll only receive a call if the lender you select needs to call you.",
                "mask": {
                    "pattern": "(000) 000-0000"
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "Y",
                "preferredCountries": "",
                "onlyCountries": "us"
            },
            "id": "f10",
            "cid": "c70"
        },
        {
            "label": "Your current residence. <br> Do you:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Own",
                        "checked": false,
                        "value": "OWN"
                    },
                    {
                        "label": "Rent",
                        "checked": false,
                        "value": "RENT"
                    },
                    {
                        "label": "Other",
                        "checked": false,
                        "value": "OTHER"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "inline"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f12",
            "cid": "c86"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class